
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: books.ramonberrutti.github.com
spec:
  group: ramonberrutti.github.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
  scope: Namespaced
  names:
    plural: books
    singular: book
    kind: Book
